version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "forward_master"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "forward_master"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - db
    env_file:
      - .env