FROM python:3.10

LABEL maintainer="me@igorduino.ru"

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --upgrade pip wheel setuptools && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "userbot.py" ] 