version: "3"

services:
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env

  userbot:
    build:
      context: .
      dockerfile: Dockerfile.userbot
    restart: always
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env