"""initial

Revision ID: 7517eafa55ee
Revises: 
Create Date: 2022-11-22 14:31:46.996125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7517eafa55ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('first_user_tg_id', sa.String(), nullable=True),
    sa.Column('second_user_tg_id', sa.String(), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_fullword', sa.Boolean(), nullable=True),
    sa.Column('replace_word', sa.String(), nullable=True),
    sa.Column('to_replace_word', sa.String(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forwards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_message_id', sa.Integer(), nullable=True),
    sa.Column('new_message_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forwards')
    op.drop_table('filters')
    op.drop_table('rules')
    op.drop_table('users')
    op.drop_table('folders')
    # ### end Alembic commands ###
